import { HubConfig, HubTheme, NotificationElement } from './types';

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? { r: parseInt(result[1], 16), g: parseInt(result[2], 16), b: parseInt(result[3], 16) }
    : { r: 168, g: 85, b: 247 };
}

function col(hex: string): string {
  const { r, g, b } = hexToRgb(hex);
  return `Color3.fromRGB(${r}, ${g}, ${b})`;
}

function getTheme(theme: HubTheme) {
  return {
    accent: col(theme.accent),
    bg: col(theme.bg),
    bgAlt: col(theme.bgAlt),
    titleColor: col(theme.titleColor || '#ffffff'),
    accentDim: (() => {
      const { r, g, b } = hexToRgb(theme.accent);
      return `Color3.fromRGB(${Math.round(r * 0.4)}, ${Math.round(g * 0.4)}, ${Math.round(b * 0.4)})`;
    })(),
  };
}

export function generateLua(config: HubConfig): string {
  const safeHubName = config.name.replace(/[^a-zA-Z0-9]/g, '') || 'Hub';
  const theme = config.theme || { accent: '#a855f7', bg: '#1a1a24', bgAlt: '#2d2d3b', preset: 'neon-purple' };
  const T = getTheme(theme);

  const width = theme.width || 560;
  const height = theme.height || 460;
  const radius = theme.borderRadius ?? 10;
  const font = theme.font || 'GothamBold';
  const opacity = (theme.opacity ?? 100) / 100;

  // Collect hub-load notifications
  const hubLoadNotifs: NotificationElement[] = [];
  config.tabs.forEach(tab => {
    tab.elements.forEach(el => {
      if (el.type === 'notification' && el.trigger === 'hub-load') {
        hubLoadNotifs.push(el as NotificationElement);
      }
    });
  });

  let lua = `-- Generated by Replit Script Hub Builder
-- Hub: ${config.name}
-- Theme: ${theme.preset}

local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer
local CoreGui = game:GetService("CoreGui")

-- Notification System
local function Notify(title, message, duration)
    pcall(function()
        game:GetService("StarterGui"):SetCore("SendNotification", {
            Title = title,
            Text = message,
            Duration = duration or 5
        })
    end)
end

-- Hub Window
local ${safeHubName} = Instance.new("ScreenGui")
${safeHubName}.Name = "${safeHubName}"
${safeHubName}.Parent = CoreGui
${safeHubName}.ResetOnSpawn = false
${safeHubName}.ZIndexBehavior = Enum.ZIndexBehavior.Sibling

local MainFrame = Instance.new("Frame")
MainFrame.Name = "MainFrame"
MainFrame.Size = UDim2.new(0, ${width}, 0, ${height})
MainFrame.Position = UDim2.new(0.5, ${-Math.floor(width / 2)}, 0.5, ${-Math.floor(height / 2)})
MainFrame.BackgroundColor3 = ${T.bg}
MainFrame.BackgroundTransparency = ${1 - opacity}
MainFrame.BorderSizePixel = 0
MainFrame.Active = true
MainFrame.Draggable = true
MainFrame.Parent = ${safeHubName}

local MainCorner = Instance.new("UICorner")
MainCorner.CornerRadius = UDim.new(0, ${radius})
MainCorner.Parent = MainFrame

local MainStroke = Instance.new("UIStroke")
MainStroke.Color = ${T.accentDim}
MainStroke.Thickness = 1
MainStroke.Parent = MainFrame

-- Title Bar
local TitleBar = Instance.new("Frame")
TitleBar.Size = UDim2.new(1, 0, 0, 45)
TitleBar.BackgroundColor3 = ${T.bgAlt}
TitleBar.BorderSizePixel = 0
TitleBar.Parent = MainFrame

local TitleBarCorner = Instance.new("UICorner")
TitleBarCorner.CornerRadius = UDim.new(0, ${radius})
TitleBarCorner.Parent = TitleBar

local TitleBarFix = Instance.new("Frame")
TitleBarFix.Size = UDim2.new(1, 0, 0.5, 0)
TitleBarFix.Position = UDim2.new(0, 0, 0.5, 0)
TitleBarFix.BackgroundColor3 = ${T.bgAlt}
TitleBarFix.BorderSizePixel = 0
TitleBarFix.Parent = TitleBar

local Title = Instance.new("TextLabel")
Title.Name = "Title"
Title.Size = UDim2.new(1, -60, 1, 0)
Title.Position = UDim2.new(0, 15, 0, 0)
Title.BackgroundTransparency = 1
Title.Text = "${config.name}"
Title.TextColor3 = ${T.titleColor}
Title.TextSize = 18
Title.TextXAlignment = Enum.TextXAlignment.Left
Title.Font = Enum.Font.${font}
Title.Parent = TitleBar

-- Close Button
local CloseBtn = Instance.new("TextButton")
CloseBtn.Size = UDim2.new(0, 30, 0, 30)
CloseBtn.Position = UDim2.new(1, -38, 0.5, -15)
CloseBtn.BackgroundColor3 = Color3.fromRGB(200, 50, 50)
CloseBtn.Text = "✕"
CloseBtn.TextColor3 = Color3.fromRGB(255,255,255)
CloseBtn.Font = Enum.Font.GothamBold
CloseBtn.TextSize = 13
CloseBtn.BorderSizePixel = 0
CloseBtn.Parent = TitleBar
Instance.new("UICorner", CloseBtn).CornerRadius = UDim.new(0, 6)
CloseBtn.MouseButton1Click:Connect(function()
    ${safeHubName}.Enabled = false
end)

-- Tab Container
local TabContainer = Instance.new("ScrollingFrame")
TabContainer.Name = "TabContainer"
TabContainer.Size = UDim2.new(1, -20, 0, 38)
TabContainer.Position = UDim2.new(0, 10, 0, 48)
TabContainer.BackgroundTransparency = 1
TabContainer.ScrollBarThickness = 0
TabContainer.CanvasSize = UDim2.new(3, 0, 0, 0)
TabContainer.Parent = MainFrame

local TabUIListLayout = Instance.new("UIListLayout")
TabUIListLayout.FillDirection = Enum.FillDirection.Horizontal
TabUIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
TabUIListLayout.Padding = UDim.new(0, 6)
TabUIListLayout.Parent = TabContainer

-- Content Container
local ContentContainer = Instance.new("Frame")
ContentContainer.Name = "ContentContainer"
ContentContainer.Size = UDim2.new(1, -20, 1, -100)
ContentContainer.Position = UDim2.new(0, 10, 0, 92)
ContentContainer.BackgroundTransparency = 1
ContentContainer.Parent = MainFrame

local TabFrames = {}
local TabButtons = {}

local function SwitchTab(tabName)
    for name, frame in pairs(TabFrames) do
        frame.Visible = (name == tabName)
    end
    for name, btn in pairs(TabButtons) do
        if name == tabName then
            btn.BackgroundColor3 = ${T.accent}
            btn.TextColor3 = Color3.fromRGB(255, 255, 255)
        else
            btn.BackgroundColor3 = ${T.bgAlt}
            btn.TextColor3 = Color3.fromRGB(180, 180, 190)
        end
    end
end

`;

  config.tabs.forEach((tab, index) => {
    const safeTabName = tab.name.replace(/[^a-zA-Z0-9]/g, '') + index;

    // Collect tab-load notifications for this tab
    const tabNotifs = tab.elements.filter(el => el.type === 'notification' && (el as NotificationElement).trigger === 'tab-load') as NotificationElement[];

    lua += `-- ===== Tab: ${tab.name} =====\n`;
    lua += `local TabBtn_${safeTabName} = Instance.new("TextButton")
TabBtn_${safeTabName}.Size = UDim2.new(0, 110, 1, 0)
TabBtn_${safeTabName}.BackgroundColor3 = ${T.bgAlt}
TabBtn_${safeTabName}.BorderSizePixel = 0
TabBtn_${safeTabName}.Text = "${tab.name}"
TabBtn_${safeTabName}.TextColor3 = Color3.fromRGB(180, 180, 190)
TabBtn_${safeTabName}.Font = Enum.Font.GothamSemibold
TabBtn_${safeTabName}.TextSize = 13
TabBtn_${safeTabName}.Parent = TabContainer
TabButtons["${safeTabName}"] = TabBtn_${safeTabName}
Instance.new("UICorner", TabBtn_${safeTabName}).CornerRadius = UDim.new(0, 6)

local TabFrame_${safeTabName} = Instance.new("ScrollingFrame")
TabFrame_${safeTabName}.Size = UDim2.new(1, 0, 1, 0)
TabFrame_${safeTabName}.BackgroundTransparency = 1
TabFrame_${safeTabName}.ScrollBarThickness = 4
TabFrame_${safeTabName}.ScrollBarImageColor3 = ${T.accent}
TabFrame_${safeTabName}.CanvasSize = UDim2.new(0, 0, 0, 0)
TabFrame_${safeTabName}.AutomaticCanvasSize = Enum.AutomaticSize.Y
TabFrame_${safeTabName}.Visible = ${index === 0 ? 'true' : 'false'}
TabFrame_${safeTabName}.Parent = ContentContainer
TabFrames["${safeTabName}"] = TabFrame_${safeTabName}

local UIListLayout_${safeTabName} = Instance.new("UIListLayout")
UIListLayout_${safeTabName}.SortOrder = Enum.SortOrder.LayoutOrder
UIListLayout_${safeTabName}.Padding = UDim.new(0, 8)
UIListLayout_${safeTabName}.Parent = TabFrame_${safeTabName}

local UIPadding_${safeTabName} = Instance.new("UIPadding")
UIPadding_${safeTabName}.PaddingBottom = UDim.new(0, 10)
UIPadding_${safeTabName}.Parent = TabFrame_${safeTabName}

TabBtn_${safeTabName}.MouseButton1Click:Connect(function()
    SwitchTab("${safeTabName}")${tabNotifs.map(n => `
    Notify("${n.title}", "${n.message}", ${n.duration})`).join('')}
end)

`;

    tab.elements.forEach((el) => {
      const safeElName = el.type + '_' + el.id.replace(/[^a-zA-Z0-9]/g, '').substring(0, 12);

      if (el.type === 'notification') {
        // Rendered as a visual label in the hub (shows what the notification is)
        if (el.trigger === 'tab-load') {
          lua += `-- Notification: ${el.label} (fires on tab load - handled in tab click above)
`;
        }
        return;
      }

      if (el.type === 'section') {
        lua += `local ${safeElName} = Instance.new("TextLabel")
${safeElName}.Size = UDim2.new(1, -5, 0, 28)
${safeElName}.BackgroundTransparency = 1
${safeElName}.Text = "  ${el.label}"
${safeElName}.TextColor3 = ${T.accent}
${safeElName}.TextXAlignment = Enum.TextXAlignment.Left
${safeElName}.Font = Enum.Font.GothamBold
${safeElName}.TextSize = 12
${safeElName}.LayoutOrder = ${tab.elements.indexOf(el)}
${safeElName}.Parent = TabFrame_${safeTabName}

`;
      } else if (el.type === 'button') {
        lua += `local ${safeElName} = Instance.new("TextButton")
${safeElName}.Size = UDim2.new(1, -5, 0, 38)
${safeElName}.BackgroundColor3 = ${T.bgAlt}
${safeElName}.BorderSizePixel = 0
${safeElName}.Text = "${el.label}"
${safeElName}.TextColor3 = Color3.fromRGB(220, 220, 230)
${safeElName}.Font = Enum.Font.GothamSemibold
${safeElName}.TextSize = 13
${safeElName}.LayoutOrder = ${tab.elements.indexOf(el)}
${safeElName}.Parent = TabFrame_${safeTabName}
Instance.new("UICorner", ${safeElName}).CornerRadius = UDim.new(0, 6)

${safeElName}.MouseButton1Click:Connect(function()
    pcall(function()
        ${el.code.split('\n').join('\n        ')}
    end)${el.notify ? `\n    Notify("${el.notify.title}", "${el.notify.message}", ${el.notify.duration})` : ''}
end)

`;
      } else if (el.type === 'toggle') {
        lua += `local ${safeElName}_State = ${el.defaultState ? 'true' : 'false'}
local ${safeElName} = Instance.new("TextButton")
${safeElName}.Size = UDim2.new(1, -5, 0, 38)
${safeElName}.BackgroundColor3 = ${T.bgAlt}
${safeElName}.BorderSizePixel = 0
${safeElName}.Text = "  ● ${el.label}"
${safeElName}.TextColor3 = ${el.defaultState ? `${T.accent}` : 'Color3.fromRGB(180, 180, 190)'}
${safeElName}.TextXAlignment = Enum.TextXAlignment.Left
${safeElName}.Font = Enum.Font.GothamSemibold
${safeElName}.TextSize = 13
${safeElName}.LayoutOrder = ${tab.elements.indexOf(el)}
${safeElName}.Parent = TabFrame_${safeTabName}
Instance.new("UICorner", ${safeElName}).CornerRadius = UDim.new(0, 6)

local ${safeElName}_Badge = Instance.new("TextLabel")
${safeElName}_Badge.Size = UDim2.new(0, 40, 0, 22)
${safeElName}_Badge.Position = UDim2.new(1, -48, 0.5, -11)
${safeElName}_Badge.BackgroundColor3 = ${el.defaultState ? `${T.accent}` : 'Color3.fromRGB(60,60,70)'}
${safeElName}_Badge.Text = ${el.defaultState ? '"ON"' : '"OFF"'}
${safeElName}_Badge.TextColor3 = Color3.fromRGB(255,255,255)
${safeElName}_Badge.Font = Enum.Font.GothamBold
${safeElName}_Badge.TextSize = 11
${safeElName}_Badge.BorderSizePixel = 0
${safeElName}_Badge.Parent = ${safeElName}
Instance.new("UICorner", ${safeElName}_Badge).CornerRadius = UDim.new(0, 4)

${safeElName}.MouseButton1Click:Connect(function()
    ${safeElName}_State = not ${safeElName}_State
    ${safeElName}_Badge.Text = ${safeElName}_State and "ON" or "OFF"
    ${safeElName}_Badge.BackgroundColor3 = ${safeElName}_State and ${T.accent} or Color3.fromRGB(60,60,70)
    ${safeElName}.TextColor3 = ${safeElName}_State and ${T.accent} or Color3.fromRGB(180,180,190)
    pcall(function()
        if ${safeElName}_State then
            ${el.codeOn.split('\n').join('\n            ')}
        else
            ${el.codeOff.split('\n').join('\n            ')}
        end
    end)
end)

${el.defaultState ? `-- Auto-run on load
pcall(function()
    ${el.codeOn.split('\n').join('\n    ')}
end)` : ''}

`;
      } else if (el.type === 'slider') {
        lua += `local ${safeElName}_Frame = Instance.new("Frame")
${safeElName}_Frame.Size = UDim2.new(1, -5, 0, 58)
${safeElName}_Frame.BackgroundColor3 = ${T.bgAlt}
${safeElName}_Frame.BorderSizePixel = 0
${safeElName}_Frame.LayoutOrder = ${tab.elements.indexOf(el)}
${safeElName}_Frame.Parent = TabFrame_${safeTabName}
Instance.new("UICorner", ${safeElName}_Frame).CornerRadius = UDim.new(0, 6)

local ${safeElName}_Label = Instance.new("TextLabel")
${safeElName}_Label.Size = UDim2.new(1, -20, 0, 22)
${safeElName}_Label.Position = UDim2.new(0, 10, 0, 4)
${safeElName}_Label.BackgroundTransparency = 1
${safeElName}_Label.Text = "${el.label}: ${el.defaultValue}"
${safeElName}_Label.TextColor3 = Color3.fromRGB(220, 220, 230)
${safeElName}_Label.TextXAlignment = Enum.TextXAlignment.Left
${safeElName}_Label.Font = Enum.Font.GothamSemibold
${safeElName}_Label.TextSize = 13
${safeElName}_Label.Parent = ${safeElName}_Frame

local ${safeElName}_Track = Instance.new("Frame")
${safeElName}_Track.Size = UDim2.new(1, -80, 0, 8)
${safeElName}_Track.Position = UDim2.new(0, 10, 0, 36)
${safeElName}_Track.BackgroundColor3 = Color3.fromRGB(40, 40, 55)
${safeElName}_Track.BorderSizePixel = 0
${safeElName}_Track.Parent = ${safeElName}_Frame
Instance.new("UICorner", ${safeElName}_Track).CornerRadius = UDim.new(1, 0)

local ${safeElName}_Fill = Instance.new("Frame")
local _pct${safeElName} = (${el.defaultValue} - ${el.min}) / math.max(1, ${el.max} - ${el.min})
${safeElName}_Fill.Size = UDim2.new(_pct${safeElName}, 0, 1, 0)
${safeElName}_Fill.BackgroundColor3 = ${T.accent}
${safeElName}_Fill.BorderSizePixel = 0
${safeElName}_Fill.Parent = ${safeElName}_Track
Instance.new("UICorner", ${safeElName}_Fill).CornerRadius = UDim.new(1, 0)

local ${safeElName}_Minus = Instance.new("TextButton")
${safeElName}_Minus.Size = UDim2.new(0, 26, 0, 24)
${safeElName}_Minus.Position = UDim2.new(1, -60, 0.5, -12)
${safeElName}_Minus.BackgroundColor3 = Color3.fromRGB(60, 60, 75)
${safeElName}_Minus.Text = "−"
${safeElName}_Minus.TextColor3 = Color3.fromRGB(220, 220, 230)
${safeElName}_Minus.Font = Enum.Font.GothamBold
${safeElName}_Minus.TextSize = 16
${safeElName}_Minus.BorderSizePixel = 0
${safeElName}_Minus.Parent = ${safeElName}_Frame
Instance.new("UICorner", ${safeElName}_Minus).CornerRadius = UDim.new(0, 4)

local ${safeElName}_Plus = Instance.new("TextButton")
${safeElName}_Plus.Size = UDim2.new(0, 26, 0, 24)
${safeElName}_Plus.Position = UDim2.new(1, -30, 0.5, -12)
${safeElName}_Plus.BackgroundColor3 = ${T.accent}
${safeElName}_Plus.Text = "+"
${safeElName}_Plus.TextColor3 = Color3.fromRGB(255, 255, 255)
${safeElName}_Plus.Font = Enum.Font.GothamBold
${safeElName}_Plus.TextSize = 16
${safeElName}_Plus.BorderSizePixel = 0
${safeElName}_Plus.Parent = ${safeElName}_Frame
Instance.new("UICorner", ${safeElName}_Plus).CornerRadius = UDim.new(0, 4)

local ${safeElName}_Value = ${el.defaultValue}
local function Update_${safeElName}()
    ${safeElName}_Label.Text = "${el.label}: " .. tostring(${safeElName}_Value)
    local pct = (${safeElName}_Value - ${el.min}) / math.max(1, ${el.max} - ${el.min})
    ${safeElName}_Fill.Size = UDim2.new(pct, 0, 1, 0)
    local value = ${safeElName}_Value
    pcall(function()
        ${el.code.split('\n').join('\n        ')}
    end)
end

local ${safeElName}_Step = math.max(1, math.floor((${el.max} - ${el.min}) / 50))
${safeElName}_Plus.MouseButton1Click:Connect(function()
    if ${safeElName}_Value < ${el.max} then
        ${safeElName}_Value = math.min(${el.max}, ${safeElName}_Value + ${safeElName}_Step)
        Update_${safeElName}()
    end
end)
${safeElName}_Minus.MouseButton1Click:Connect(function()
    if ${safeElName}_Value > ${el.min} then
        ${safeElName}_Value = math.max(${el.min}, ${safeElName}_Value - ${safeElName}_Step)
        Update_${safeElName}()
    end
end)

`;
      }
    });
  });

  if (config.tabs.length > 0) {
    const firstTabSafeName = config.tabs[0].name.replace(/[^a-zA-Z0-9]/g, '') + '0';
    lua += `SwitchTab("${firstTabSafeName}")\n`;
  }

  lua += `
-- Toggle visibility with RightAlt key
game:GetService("UserInputService").InputBegan:Connect(function(input, processed)
    if not processed and input.KeyCode == Enum.KeyCode.RightAlt then
        ${safeHubName}.Enabled = not ${safeHubName}.Enabled
    end
end)

`;

  // Hub-load notifications (fire once at the end)
  if (hubLoadNotifs.length > 0) {
    hubLoadNotifs.forEach(n => {
      lua += `Notify("${n.title}", "${n.message}", ${n.duration})\n`;
    });
  } else {
    lua += `Notify("${config.name}", "Hub loaded! Press RightAlt to toggle.", 5)\n`;
  }

  return lua;
}
